-- Expanded ingredient substitutions: beans, produce, ethnic, canned goods, etc.
INSERT IGNORE INTO ingredient_substitutions (ingredient, substitute, ratio, notes) VALUES

-- Bean varieties
('kidney beans', 'pinto beans', '1:1', 'Similar texture, slightly different flavor'),
('kidney beans', 'black beans', '1:1', 'Firmer texture, works in chili and soups'),
('kidney beans', 'cannellini beans', '1:1', 'Milder flavor, great in Italian dishes'),
('chili beans', 'kidney beans', '1:1', 'Add chili powder to match seasoning'),
('chili beans', 'pinto beans', '1:1', 'Add chili powder to match seasoning'),
('chili beans', 'black beans', '1:1', 'Slightly different texture, works well'),
('black beans', 'kidney beans', '1:1', 'Softer texture, milder flavor'),
('black beans', 'pinto beans', '1:1', 'Common swap in Mexican dishes'),
('pinto beans', 'kidney beans', '1:1', 'Firmer texture, holds shape better'),
('navy beans', 'great northern beans', '1:1', 'Very similar, slightly larger'),
('navy beans', 'cannellini beans', '1:1', 'Larger but same mild flavor'),
('cannellini beans', 'great northern beans', '1:1', 'Slightly smaller, same flavor'),
('lima beans', 'butter beans', '1:1', 'Same bean, different name'),
('lima beans', 'edamame', '1:1', 'Different flavor, similar texture'),
('chickpeas', 'white beans', '1:1', 'Different texture, works in most recipes'),
('lentils', 'split peas', '1:1', 'Similar cook time, earthier flavor'),
('red lentils', 'yellow lentils', '1:1', 'Very similar, cooks the same'),

-- Canned goods
('canned tomatoes', 'fresh tomatoes', '1 can = 2 cups chopped', 'Fresh are less acidic, may need longer cooking'),
('canned tomatoes', 'tomato sauce', '1 can = 1 cup sauce + 1 cup water', 'Smoother texture'),
('tomato paste', 'tomato sauce', '1 tbsp paste = 3 tbsp sauce', 'Reduce other liquid in recipe'),
('tomato sauce', 'canned tomatoes', '1:1', 'Blend canned tomatoes for sauce'),
('coconut milk', 'coconut cream', '1:1', 'Thicker, richer — add water to thin'),
('coconut milk', 'oat milk', '1:1', 'Less rich, no coconut flavor'),
('evaporated milk', 'heavy cream', '1:1', 'Richer, not reduced'),
('evaporated milk', 'coconut milk', '1:1', 'Dairy-free option'),
('condensed milk', 'coconut condensed milk', '1:1', 'Dairy-free, similar sweetness'),
('canned corn', 'frozen corn', '1:1', 'Thaw and drain before using'),
('canned green beans', 'frozen green beans', '1:1', 'Better texture when frozen'),

-- Produce varieties
('sweet potato', 'butternut squash', '1:1', 'Similar sweetness and texture'),
('sweet potato', 'regular potato', '1:1', 'Less sweet, different flavor'),
('butternut squash', 'acorn squash', '1:1', 'Similar flavor, different shape'),
('butternut squash', 'pumpkin', '1:1', 'Very similar flavor and texture'),
('zucchini', 'yellow squash', '1:1', 'Almost identical in cooking'),
('zucchini', 'cucumber', '1:1', 'Only for raw/salad use'),
('spinach', 'kale', '1:1', 'Kale needs more cooking time'),
('spinach', 'swiss chard', '1:1', 'Very similar when cooked'),
('kale', 'collard greens', '1:1', 'Similar heartiness, different flavor'),
('arugula', 'watercress', '1:1', 'Both peppery, similar use'),
('romaine lettuce', 'butter lettuce', '1:1', 'Softer, milder flavor'),
('bell pepper', 'poblano pepper', '1:1', 'Mild heat, similar use'),
('jalapeño', 'serrano pepper', '1:1', 'Hotter, use less'),
('jalapeño', 'green chiles', '1:1', 'Milder, canned are convenient'),
('mushrooms', 'portobello mushrooms', '1:1', 'Larger, meatier texture'),
('mushrooms', 'cremini mushrooms', '1:1', 'Same species, slightly more flavor'),
('broccoli', 'cauliflower', '1:1', 'Milder flavor, same texture'),
('green beans', 'asparagus', '1:1', 'Different flavor, similar texture'),
('celery', 'fennel', '1:1', 'Anise flavor, similar crunch'),
('corn', 'peas', '1:1', 'Different flavor, similar sweetness'),

-- Ethnic / specialty
('fish sauce', 'soy sauce', '1:1', 'Less funky, good in a pinch'),
('fish sauce', 'worcestershire sauce', '1:1', 'Similar umami depth'),
('miso paste', 'soy sauce', '1 tbsp miso = 1/2 tbsp soy', 'Liquid vs paste, adjust accordingly'),
('miso paste', 'tahini', '1:1', 'No umami, but similar in dressings'),
('tahini', 'peanut butter', '1:1', 'Stronger flavor, check for allergies'),
('tahini', 'sunflower seed butter', '1:1', 'Nut-free alternative'),
('gochujang', 'sriracha + miso', '1:1', 'Mix equal parts for similar flavor'),
('gochujang', 'sambal oelek', '1:1', 'Less sweet, more heat'),
('hoisin sauce', 'barbecue sauce', '1:1', 'Different flavor profile but similar use'),
('rice vinegar', 'apple cider vinegar', '1:1', 'Slightly stronger, works well'),
('rice vinegar', 'white wine vinegar', '1:1', 'More acidic, use slightly less'),
('sesame oil', 'peanut oil', '1:1', 'Less nutty, higher smoke point'),
('coconut aminos', 'soy sauce', '1:1', 'Soy-free alternative, less salty'),
('tamari', 'soy sauce', '1:1', 'Tamari is gluten-free, similar taste'),
('curry paste', 'curry powder', '1 tbsp paste = 1 tsp powder', 'Add oil and garlic to powder'),
('lemongrass', 'lemon zest', '1 stalk = 1 tsp zest', 'Less complex but similar citrus'),
('galangal', 'ginger', '1:1', 'More floral than ginger but works'),
('kaffir lime leaves', 'lime zest', '1 leaf = 1/2 tsp zest', 'Less aromatic but adds citrus'),
('sambal oelek', 'red pepper flakes', '1 tsp sambal = 1/2 tsp flakes', 'Less complex, just heat'),
('harissa', 'sriracha', '1:1', 'Different flavor profile, similar heat'),
('chipotle in adobo', 'smoked paprika + cayenne', '1 pepper = 1 tsp paprika + pinch cayenne', 'Smoky heat without the sauce'),

-- Nuts and seeds
('almonds', 'cashews', '1:1', 'Softer, slightly sweeter'),
('almonds', 'pecans', '1:1', 'Richer, buttery flavor'),
('walnuts', 'pecans', '1:1', 'Both work in baking and salads'),
('pine nuts', 'sunflower seeds', '1:1', 'Much cheaper, similar use in pesto'),
('pine nuts', 'cashews', '1:1', 'Creamy, works in pesto'),
('peanuts', 'cashews', '1:1', 'Different flavor, similar crunch'),
('sesame seeds', 'hemp seeds', '1:1', 'Nuttier, more protein'),
('chia seeds', 'flax seeds', '1:1', 'Both work as egg replacer and thickener'),

-- Grains and pasta
('white rice', 'brown rice', '1:1', 'Longer cook time, more nutritious'),
('white rice', 'cauliflower rice', '1:1', 'Low carb, microwave or sauté'),
('quinoa', 'couscous', '1:1', 'Faster cooking, different texture'),
('quinoa', 'bulgur', '1:1', 'Similar nutrition, nuttier flavor'),
('elbow macaroni', 'penne', '1:1', 'Different shape, same cook time'),
('elbow macaroni', 'rotini', '1:1', 'Holds sauce well'),
('spaghetti', 'linguine', '1:1', 'Slightly wider, same use'),
('spaghetti', 'angel hair', '1:1', 'Thinner, cooks faster'),
('egg noodles', 'pappardelle', '1:1', 'Wider, same egg-based dough'),
('bread crumbs', 'panko', '1:1', 'Crunchier, lighter coating'),
('bread crumbs', 'crushed crackers', '1:1', 'Adds flavor, same binding'),
('tortillas', 'lettuce wraps', '1:1', 'Low carb alternative'),
('pita bread', 'naan', '1:1', 'Different texture, similar use'),

-- Sweeteners
('white sugar', 'brown sugar', '1:1', 'Adds moisture and slight molasses flavor'),
('white sugar', 'honey', '3/4 cup per 1 cup', 'Reduce other liquids, lower oven temp 25°F'),
('white sugar', 'maple syrup', '3/4 cup per 1 cup', 'Reduce other liquids'),
('brown sugar', 'white sugar + molasses', '1 cup = 1 cup white + 1 tbsp molasses', 'DIY brown sugar'),
('honey', 'agave nectar', '1:1', 'Vegan alternative, similar sweetness'),
('corn syrup', 'golden syrup', '1:1', 'British equivalent, slightly different flavor'),
('powdered sugar', 'white sugar', 'blend 1 cup sugar + 1 tbsp cornstarch', 'Homemade powdered sugar'),

-- Dairy alternatives (extended)
('butter', 'ghee', '1:1', 'Clarified butter, higher smoke point, nutty flavor'),
('buttermilk', 'milk + lemon juice', '1 cup = 1 cup milk + 1 tbsp lemon juice', 'Let sit 5 minutes'),
('buttermilk', 'milk + vinegar', '1 cup = 1 cup milk + 1 tbsp white vinegar', 'Let sit 5 minutes'),
('ricotta', 'cottage cheese', '1:1', 'Blend for smoother texture'),
('ricotta', 'mascarpone', '1:1', 'Richer, less grainy'),
('feta', 'goat cheese', '1:1', 'Creamier, less salty'),
('cheddar', 'gruyère', '1:1', 'Nuttier, melts beautifully'),
('swiss cheese', 'gruyère', '1:1', 'Very similar, slightly nuttier'),

-- Proteins (extended)
('ground beef', 'ground turkey', '1:1', 'Leaner, add fat if needed'),
('ground beef', 'ground pork', '1:1', 'Similar fat content, different flavor'),
('ground beef', 'lentils', '1:1', 'Vegan, add spices for depth'),
('ground beef', 'impossible meat', '1:1', 'Plant-based, similar cooking'),
('chicken breast', 'turkey breast', '1:1', 'Very similar, slightly leaner'),
('chicken breast', 'pork tenderloin', '1:1', 'Similar lean protein'),
('chicken thighs', 'pork shoulder', '1:1', 'Both benefit from slow cooking'),
('salmon', 'arctic char', '1:1', 'Similar flavor and texture'),
('salmon', 'trout', '1:1', 'Milder flavor, similar texture'),
('shrimp', 'scallops', '1:1', 'Different texture, similar cooking'),
('tuna', 'swordfish', '1:1', 'Similar meaty texture'),
('bacon', 'turkey bacon', '1:1', 'Leaner, less crispy'),
('bacon', 'pancetta', '1:1', 'Italian, unsmoked'),
('sausage', 'chorizo', '1:1', 'Spicier, adds paprika flavor'),
('tofu', 'tempeh', '1:1', 'Firmer, nuttier flavor'),
('tofu', 'paneer', '1:1', 'Not vegan, but similar texture');
